### ISSUE TITLE
Twitter authentication showing error

### ISSUE THREAD

**Issue by santhoshrao519** [jaychang0917/SimpleAuth#18]
When click on twitter icon, the app is showing following error

failed to get request token
                                        com.twitter.sdk.android.core.TwitterApiException: HTTP request failed, Status: 401
                                            at com.twitter.sdk.android.core.Callback.onResponse(Callback.java:42)
                                            at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
                                            at android.os.Handler.handleCallback(Handler.java:751)
                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                            at android.os.Looper.loop(Looper.java:154)
                                            at android.app.ActivityThread.main(ActivityThread.java:6776)
                                            at java.lang.reflect.Method.invoke(Native Method)
                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by jaychang0917** [comment]
Pls provide your demo code

**Comment by santhoshrao519** [comment]
Didn't get you..pls elaborate once

**Comment by jaychang0917** [comment]
Pls check this [stackoverflow post](https://stackoverflow.com/questions/33228235/failed-to-get-request-token-on-android-m-running-devices)
